name: Release LaTeX document

on:
    push:
        tags:
            - "v*"

permissions:
    contents: write

jobs:
    build_release_latex:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: rename main pdf
              run: cp main.pdf 模板说明.pdf

            - name: Upload Pdf to GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      模板说明.pdf
                      tutemplate.sty
                      tutorial/tutorial.pdf
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
